### ISSUE TITLE
TA comment: 使用案例圖

### ISSUE THREAD

**Issue by TDyu** [fcu-d0673063/BaseProject-Cpp#2]
1. 這完全不是use case，請熟悉use case後重新繪製（-60）

*若有修改，請在此issue下回覆，否則不予修改及加分。

**Comment by fcu-d0598299** [comment]
已修改

**Comment by TDyu** [comment]
> 已修改

OK 已修改ilearn上分數

不過建議Actor和那3個case可以直接分別連起來
